apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  # Number of pods to replicate.
  replicas: 2

  # Helps to identify which pods to manage. More sophisticated selection rules are possible than just using the template's label.
  selector:
    # Specify a label that can be found in this spec's template for pods.
    matchLabels:
      app: nodejs-pod

  # Template for pods
  template:
    # Specify info that will help in identifying this template.
    metadata:
      labels:
        app: nodejs-pod

    # The desired attributes of this templates containers and such.
    spec:
      # A list of containers to create. We could create a Nodejs container, a Postgres container, a Redis container all in one pod.
      containers:
      - name: nodejs-container
        image: folushooladipo/simple-node
        ports:
        - containerPort: 80
